# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd70f72c5f2e32b0953359a4660809c7f26c9ddace67efaf1e71017cd5183ea254047dbcae4aaf9b033233a6277ce2ae3f004fa5329a09836841de83f134ab4

test:
  secret_key_base: e12dada2baddae1c9faabe61b8715af63c086e401e71e8f941c833f46c336db5a08e0e5943b4a7c949711bd6634c5f5b42b7bf0864f4272fd45f1316017eaa1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
